# Generated by Django 3.1 on 2020-09-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterisk', '0002_auto_20200906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extentions',
            name='exten',
            field=models.CharField(max_length=30),
        ),
    ]
